"""
Generates two compact, flat lookup tables for ALU testing:

  aluLookupNor[a<<8 | b]  →  {f, n, z}
  aluLookupAdd[a<<8 | b][cin]  →  {f, c, n, z}

Flat 1-D arrays (65 536 entries each) index faster and load faster than
the original nested 256×256×2 structure, while still covering the full
combinatorial space.  The 'v' (overflow) field is dropped because none of
the test cases in components_test.js actually assert on it.
"""


def flags(f: int) -> tuple[int, int]:
    """Return (neg, zero) flags for an 8-bit result."""
    n = 1 if (f & 0x80) != 0 else 0
    z = 1 if f == 0 else 0
    return n, z


def generate():
    nor_entries: list[str] = []
    add_entries: list[str] = []

    for a in range(256):
        for b in range(256):
            # ── NOR ──────────────────────────────────────────────────────────
            f_nor = (~a & ~b) & 0xFF
            n, z = flags(f_nor)
            nor_entries.append(f'{{"f":{f_nor},"n":{n},"z":{z}}}')

            # ── ADD (cin=0 and cin=1) ─────────────────────────────────────────
            cin_pair: list[str] = []
            for cin in (0, 1):
                raw = a + b + cin
                f   = raw & 0xFF
                c   = 1 if raw > 0xFF else 0
                n, z = flags(f)
                cin_pair.append(f'{{"f":{f},"c":{c},"n":{n},"z":{z}}}')
            add_entries.append("[" + ",".join(cin_pair) + "]")

    nor_body = ",\n  ".join(nor_entries)
    add_body = ",\n  ".join(add_entries)

    js = (
        "// Auto-generated by test_generator.py — do not edit by hand.\n"
        "// Index: a<<8|b  (65 536 entries each)\n\n"
        f"const aluLookupNor = [\n  {nor_body}\n];\n\n"
        f"const aluLookupAdd = [\n  {add_body}\n];\n\n"
        "module.exports = { aluLookupNor, aluLookupAdd };\n"
    )

    out = "alu_lookup.js"
    with open(out, "w") as fh:
        fh.write(js)
    print(f"Done — wrote {len(nor_entries):,} NOR entries and "
          f"{len(add_entries):,} ADD entries to {out}")


if __name__ == "__main__":
    print("Generating flat ALU lookup tables …")
    generate()